name: raspberrypistreamer
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  firebase: ^9.0.2
  infinite_scroll_pagination: ^3.1.0
  http: ^0.13.4
  flutter_staggered_grid_view: ^0.6.1
  transparent_image: any

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

